name: github_search
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.6.0
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  logger: ^2.0.1
  flutter_riverpod: ^2.4.9
  font_awesome_flutter: ^10.4.0
  go_router: ^10.1.2
  webview_flutter: ^4.2.2
  url_launcher: ^6.1.11
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

